### ISSUE TITLE
To Do: Create Simplified eFSKX Format Based on FSKX Spec

### ISSUE THREAD

**Issue by ZarskeM** [KIDA-BfR/eFSKX#1]
## Topic: Creation of a Reduced eFSKX Format Based on FSKX

**Description:**
This issue is to support the development of a reduced version of the standard FSKX format. This version focuses on the essentials and refers to the existing FSKX guidance document where applicable.

**Objectives:**
- Simplify and reduce the format
- Ensure that all key sections from the FSKX format are adequately referenced

---

### To-Do List Based on Comments:

- [ ] **Specify references to FSKX:**
  - Refer to the FSKX document for sections already described in detail.

- [ ] **Delete not needed sections:**
  - Review the document and delete not needed sections (e.g. Typographical conventions).

- [ ] **Merge model and data description in tables 1&2:**
  - Find an appropiate way to combine model and data so that the designated column "mandatory for" can be deleted

- [ ] **Update Figure 2:**
  - Adjust the Figure 2 after all changes on the document have been made
  - Add an example of the smallest possible eFSKX file

- [ ] **Revise needed sections in FSKX guidance document:**
  - Ensure that specific setions are also revised in the FSKX document (e.g. Metadata RDF file, Controlled vocabulary, Required Software and Packages, etc.)

- [ ] **Provide example FSKX files as download link:**
  - The FSKX files regarding the examples for a basic model or dataset should be provided as download.

---

**Additional Resources:**
References to the FSKX document: G:\Abteilung-4\Public\FoodRisk-Labs\RAKIP\9. FSK-ML_Guidance document\reduced Version proposal
[FSK_guidance_document_reduced - draft 2_TS_MF.docx](https://github.com/user-attachments/files/16989226/FSK_guidance_document_reduced.-.draft.2_TS_MF.docx)
